# Generated by Django 5.1 on 2024-08-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=500)),
                ("color_identities", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mana_cost", models.CharField(blank=True, max_length=50, null=True)),
                ("mana_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type_line", models.CharField(max_length=255)),
                (
                    "oracle_text",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("keywords", models.CharField(blank=True, max_length=500, null=True)),
                ("power", models.IntegerField(blank=True, null=True)),
                ("toughness", models.IntegerField(blank=True, null=True)),
                (
                    "color_identity",
                    models.CharField(
                        choices=[
                            ("W", "White"),
                            ("U", "Blue"),
                            ("B", "Black"),
                            ("R", "Red"),
                            ("G", "Green"),
                            ("C", "Colorless"),
                            ("WU", "White-Blue"),
                            ("WB", "White-Black"),
                            ("WR", "White-Red"),
                            ("WG", "White-Green"),
                            ("UB", "Blue-Black"),
                            ("UR", "Blue-Red"),
                            ("UG", "Blue-Green"),
                            ("BR", "Black-Red"),
                            ("BG", "Black-Green"),
                            ("RG", "Red-Green"),
                            ("WUB", "White-Blue-Black"),
                            ("WUR", "White-Blue-Red"),
                            ("WUG", "White-Blue-Green"),
                            ("WBR", "White-Black-Red"),
                            ("WBG", "White-Black-Green"),
                            ("WRG", "White-Red-Green"),
                            ("UBR", "Blue-Black-Red"),
                            ("UBG", "Blue-Black-Green"),
                            ("URG", "Blue-Red-Green"),
                            ("BRG", "Black-Red-Green"),
                            ("WUBR", "White-Blue-Black-Red"),
                            ("WUBG", "White-Blue-Black-Green"),
                            ("WURG", "White-Blue-Red-Green"),
                            ("WBRG", "White-Black-Red-Green"),
                            ("UBRG", "Blue-Black-Red-Green"),
                            ("WUBRG", "White-Blue-Black-Red-Green"),
                        ],
                        max_length=10,
                    ),
                ),
                ("set_name", models.CharField(max_length=255)),
                ("rarity", models.CharField(max_length=50)),
                ("edhrec_rank", models.IntegerField()),
                ("img_url", models.URLField()),
                ("archetypes", models.ManyToManyField(to="cube_generator.archetype")),
            ],
        ),
        migrations.CreateModel(
            name="Cube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                ("color_identities", models.CharField(max_length=10)),
                ("archetypes", models.ManyToManyField(to="cube_generator.archetype")),
                ("cards", models.ManyToManyField(to="cube_generator.card")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
