# Generated by Django 5.1 on 2024-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="scryfall_id",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
