# Generated by Django 5.1 on 2024-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube_generator", "0002_card_scryfall_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="scryfall_id",
            field=models.CharField(max_length=255),
        ),
    ]
